addons:
  code_climate:
    repo_token: c75df5383c6ed506f57bd7281c1c41200a139a6847ad4c62d0371a23d457f8c6
language: ruby
rvm:
- 2.1.2
before_script:
- cp config/database.psql.yml config/database.yml
- psql -c 'create database hpi_swt2_test;' -U postgres
notifications:
  email: false
deploy:
  provider: heroku
  api_key:
    secure: 8eae5a00-c33d-4505-b6ff-2e0d8db4d9b8
  app: event-und-raumplanung-biber
  on:
    repo: Atyanar/event-und-raumplanung-biber
    branch: dev